// <auto-generated />
using System;
using ConfLog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConfLog.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20220608170741_Initial11")]
    partial class Initial11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ConfLog.Models.CartItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Checked")
                        .HasColumnType("bit");

                    b.Property<int>("funcid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("funcid");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ConfLog.Models.FType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("functionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("FType");
                });

            modelBuilder.Entity("ConfLog.Models.Function", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Orderid")
                        .HasColumnType("int");

                    b.Property<int?>("Usingid")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("desk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isBase")
                        .HasColumnType("bit");

                    b.Property<int?>("level")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("typeID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Orderid");

                    b.HasIndex("Usingid");

                    b.HasIndex("typeID");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("ConfLog.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("orderTime")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ConfLog.Models.Using", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Orderid")
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Orderid");

                    b.ToTable("Using");
                });

            modelBuilder.Entity("ConfLog.Models.CartItem", b =>
                {
                    b.HasOne("ConfLog.Models.Function", "func")
                        .WithMany()
                        .HasForeignKey("funcid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("func");
                });

            modelBuilder.Entity("ConfLog.Models.Function", b =>
                {
                    b.HasOne("ConfLog.Models.Order", null)
                        .WithMany("functions")
                        .HasForeignKey("Orderid");

                    b.HasOne("ConfLog.Models.Using", null)
                        .WithMany("functions")
                        .HasForeignKey("Usingid");

                    b.HasOne("ConfLog.Models.FType", "type")
                        .WithMany("functions")
                        .HasForeignKey("typeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("type");
                });

            modelBuilder.Entity("ConfLog.Models.Using", b =>
                {
                    b.HasOne("ConfLog.Models.Order", null)
                        .WithMany("usings")
                        .HasForeignKey("Orderid");
                });

            modelBuilder.Entity("ConfLog.Models.FType", b =>
                {
                    b.Navigation("functions");
                });

            modelBuilder.Entity("ConfLog.Models.Order", b =>
                {
                    b.Navigation("functions");

                    b.Navigation("usings");
                });

            modelBuilder.Entity("ConfLog.Models.Using", b =>
                {
                    b.Navigation("functions");
                });
#pragma warning restore 612, 618
        }
    }
}
